#!/bin/bash --login
#SBATCH -D .
#SBATCH -J ADCIRC_GAHM_GENERIC
#SBATCH --mail-type=all
#SBATCH --mail-user=zachary.burnett@noaa.gov
#SBATCH --output=mannings_n_perturbation.log
#SBATCH -N 5
#SBATCH --tasks-per-node=68
#SBATCH --time=02:00:00
#SBATCH --partition=development

set -e

module load intel impi netcdf

PATH=$HOME/adcirc/build:$PATH

main() {
  for directory in */; do
    echo "Starting configuration $directory..."
    cd "$directory"
    SECONDS=0
    run_coldstart_phase
    if grep -Rq "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping." mannings_n_perturbation.log; then
      duration=$SECONDS
      echo "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping."
      echo "Wallclock time: $($duration / 60) minutes and $($duration % 60) seconds."
      exit -1
    else
      run_hotstart_phase
      duration=$SECONDS
      if grep -Rq "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping." mannings_n_perturbation.log; then
        echo "ERROR: Elevation.gt.ErrorElev, ADCIRC stopping."
        echo "Wallclock time: $($duration / 60) minutes and $($duration % 60) seconds."
        exit -1
      fi
    fi
    echo "Wallclock time: $($duration / 60) minutes and $($duration % 60) seconds."
    cd ../
  done
}

run_coldstart_phase() {
  rm -rf coldstart
  mkdir coldstart
  cd coldstart
  ln -sf ../fort.14
  ln -sf ../fort.13
  ln -sf ../fort.15.coldstart ./fort.15
  adcprep --np $SLURM_NTASKS --partmesh
  adcprep --np $SLURM_NTASKS --prepall
  ibrun padcirc
  clean_directory
  cd ..
}

run_hotstart_phase() {
  rm -rf hotstart
  mkdir hotstart
  cd hotstart
  ln -sf ../fort.14
  ln -sf ../fort.13
  ln -sf ../fort.15.hotstart ./fort.15
  ln -sf ../coldstart/fort.67.nc
  adcprep --np $SLURM_NTASKS --partmesh
  adcprep --np $SLURM_NTASKS --prepall
  ibrun padcirc
  clean_directory
  cd ..
}

clean_directory() {
  rm -rf PE*
  rm -rf partmesh.txt
  rm -rf metis_graph.txt
  rm -rf fort.13
  rm -rf fort.14
  rm -rf fort.15
  rm -rf fort.16
  rm -rf fort.80
  rm -rf fort.68.nc
}

main
