name: formatting

on: pull_request

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v2
      - name: install Python
        uses: actions/setup-python@v2
      - name: install dependencies
        run: pip install ".[development]"
      - name: run linters / formatters
        uses: wearerequired/lint-action@master
        with:
          oitnb_command_prefix: isort --fss --fass .;
          oitnb: true
          auto_fix: true
