name: formatting

on: pull_request

jobs:
  run-linters:
    name: Run formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
      - name: Install dependencies
        run: |
          pip install wheel
          pip install -e .[development]
      - name: Run linters / formatters
        uses: wearerequired/lint-action@master
        with:
          oitnb_command_prefix: isort --fss --fass .;
          oitnb: true
          auto_fix: true
